name: Release Build
on:
  push:
    tags:
      - 'v[0-9].[0-9]+.[0-9]+'
env:
  GO_VERSION: 1.19.6

jobs:
  Build:
    strategy:
      matrix:
        arch: [ amd64, arm64 ]
    runs-on: ubuntu-20.04
    env:
      GOARCH: ${{ matrix.arch }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Build ${{ env.GOARCH }} artifact
        run: make build

      - name: Rename binary
        run: mv bin/spire-agent bin/spire-agent-${GOARCH}

      - name: Push ${{ env.GOARCH }} artifact
        uses: actions/upload-artifact@v3
        with:
          name: spire-agent-${{ env.GOARCH }}
          path: bin/spire-agent-${{ env.GOARCH }}

  Publish:
    runs-on: ubuntu-20.04
    needs: [ Build ]
    permissions:
      contents: write

    steps:
      - name: Pull artifact
        uses: actions/download-artifact@v3
        with:
          name: spire-agent-amd64
          path: artifacts/

      - name: Pull artifact
        uses: actions/download-artifact@v3
        with:
          name: spire-agent-arm64
          path: artifacts/

      - name: Create tarball
        run: |
          mv artifacts/spire-agent-amd64 artifacts/spire-agent-x86_64
          mv artifacts/spire-agent-arm64 artifacts/spire-agent-aarch64
          tar -cvzf spire-agent-${GITHUB_REF##*/}-linux-multiarch.tgz -C artifacts .

      - name: Create release
        uses: ncipollo/release-action@v1
        with:
          generateReleaseNotes: true
          artifacts: "spire-agent-*.tgz"
